version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/gitoracle:cached
    command: sleep infinity
    working_dir: /workspaces/gitoracle
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: gitoracle
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
